apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    service: cart
  name: cart
spec:
  replicas: 1
  selector:
    service: cart
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: cart
    spec:
      containers:
      - env:
        - name: APP_OPTIONS
          value: --port=10001 --db=cart-db.sock --zipkin=zipkin.sock
        image: ' '
        name: cart
        resources: {}
        ports:
        - containerPort: 10001
          hostPort: 10001
          protocol: TCP
        livenessProbe:
          httpGet:
            host: localhost
            path: /health
            port: 10001
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            host: localhost
            path: /health
            port: 10001
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /tmp
          name: cart-tmpfs0
      hostNetwork: true
      restartPolicy: Always
      volumes:
      - emptyDir:
          medium: Memory
        name: cart-tmpfs0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - cart
      from:
        kind: ImageStreamTag
        name: cart:latest
    type: ImageChange
status: {}
