apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    service: edge-router
  name: edge-router
spec:
  replicas: 1
  selector:
    service: edge-router
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: edge-router
    spec:
      containers:
      - args:
        - traefik
        - --web.address=:10007
        - --entryPoints=Name:http Address::10008
        image: ' '
        name: edge-router
        ports:
        - containerPort: 10007
          hostPort: 10007
          protocol: TCP
        - containerPort: 10008
          hostPort: 10008
          protocol: TCP
        resources: {}
        ports:
        - containerPort: 10007
          hostPort: 10007
          protocol: TCP
        livenessProbe:
          httpGet:
            host: localhost
            path: /health
            port: 10007
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            host: localhost
            path: /health
            port: 10007
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/traefik/
          name: config-volume
        - mountPath: /var/run
          name: edge-router-tmpfs0
      hostNetwork: true
      restartPolicy: Always
      volumes:
      - name: config-volume
        configMap:
          name: edge-router
      - emptyDir:
          medium: Memory
        name: edge-router-tmpfs0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - edge-router
      from:
        kind: ImageStreamTag
        name: edge-router:latest
    type: ImageChange
status: {}
