apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    service: front-end
  name: front-end
spec:
  replicas: 1
  selector:
    service: front-end
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: front-end
    spec:
      containers:
      - env:
        - name: PORT
          value: "10009"
        - name: NPM_RUN
          value: start -- --domain=sock
        image: ' '
        name: front-end
        ports:
        - containerPort: 10009
          hostPort: 10009
          protocol: TCP
        livenessProbe:
          tcpSocket:
            host: localhost
            port: 10009
          initialDelaySeconds: 10
        readinessProbe:
          tcpSocket:
            host: localhost
            port: 10009
          initialDelaySeconds: 10
      hostNetwork: true
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - front-end
      from:
        kind: ImageStreamTag
        name: front-end:latest
    type: ImageChange
status: {}
