apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    service: load-test
  name: load-test
spec:
  replicas: 1
  selector:
    service: load-test
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: load-test
    spec:
      containers:
      - command:
        - /opt/app-root/scripts/run
        - -h sock.192.168.64.2.xip.io 
        image: ' '
        name: load-test
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - load-test
      from:
        kind: ImageStreamTag
        name: load-test:latest
    type: ImageChange
status: {}
