apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    service: orders
  name: orders
spec:
  replicas: 1
  selector:
    service: orders
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: orders
    spec:
      containers:
      - env:
        - name: APP_OPTIONS
          value: --port=10002 --db=orders-db.sock --zipkin=zipkin.sock --server.payment.host=payment.sock --server.shipping.host=shipping.sock
        image: ' '
        name: orders
        resources: {}
        ports:
        - containerPort: 10002
          hostPort: 10002
          protocol: TCP
        livenessProbe:
          httpGet:
            host: localhost
            path: /health
            port: 10002
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            host: localhost
            path: /health
            port: 10002
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /tmp
          name: orders-tmpfs0
      hostNetwork: true
      restartPolicy: Always
      volumes:
      - emptyDir:
          medium: Memory
        name: orders-tmpfs0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - orders
      from:
        kind: ImageStreamTag
        name: orders:latest
    type: ImageChange
status: {}
