apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    service: orders-db
  name: orders-db
spec:
  replicas: 1
  selector:
    service: orders-db
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: orders-db
    spec:
      containers:
      - image: ' '
        name: orders-db
        resources: {}
        volumeMounts:
        - mountPath: /data/configdb
          name: orders-db-empty0
        - mountPath: /data/db
          name: orders-db-empty1
        - mountPath: /tmp
          name: orders-db-tmpfs0
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: orders-db-empty0
      - emptyDir: {}
        name: orders-db-empty1
      - emptyDir:
          medium: Memory
        name: orders-db-tmpfs0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - orders-db
      from:
        kind: ImageStreamTag
        name: orders-db:latest
    type: ImageChange
status: {}
