apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: payment
  name: payment
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 10005
  selector:
    service: payment
status:
  loadBalancer: {}
