apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    service: payment
  name: payment
spec:
  replicas: 1
  selector:
    service: payment
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: payment
    spec:
      containers:
      - args:
        - scripts/run
        - -port=10005
        - -decline=200
        env:
        - name: ZIPKIN
          value: http://zipkin.sock:9411/api/v1/spans
        image: ' '
        name: payment
        resources: {}
        ports:
        - containerPort: 10005
          hostPort: 10005
          protocol: TCP
        livenessProbe:
          httpGet:
            host: localhost
            path: /health
            port: 10005
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            host: localhost
            path: /health
            port: 10005
            scheme: HTTP
          timeoutSeconds: 1
          initialDelaySeconds: 10
      hostNetwork: true
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - payment
      from:
        kind: ImageStreamTag
        name: payment:latest
    type: ImageChange
status: {}
