apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: queue-master
  name: queue-master
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 10004
  selector:
    service: queue-master
status:
  loadBalancer: {}
