apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: shipping
  name: shipping
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 10003
  selector:
    service: shipping
status:
  loadBalancer: {}
