apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: user
  name: user
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 10006
  selector:
    service: user
status:
  loadBalancer: {}
