apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    service: zipkin
  name: zipkin
spec:
  replicas: 1
  selector:
    service: zipkin
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: zipkin
    spec:
      containers:
      - image: ' '
        name: zipkin
        ports:
        - containerPort: 9411
        resources: {}
        volumeMounts:
        - mountPath: /tmp
          name: zipkin-tmpfs0
      restartPolicy: Always
      volumes:
      - emptyDir:
        name: zipkin-tmpfs0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - zipkin
      from:
        kind: ImageStreamTag
        name: zipkin:latest
    type: ImageChange
status: {}
