apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: catalogue
  name: catalogue
spec:
  ports:
  - name: '8080'
    protocol: TCP
    port: 8080
    targetPort: 10000
  selector:
    service: catalogue
  type: ClusterIP
status:
  loadBalancer: {}
