apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: catalogue-db
  name: catalogue-db
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: catalogue-db
status:
  loadBalancer: {}
