apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: edge-router
  name: edge-router
spec:
  ports:
  - name: "10007"
    port: 10007
    targetPort: 10007
  - name: "10008"
    port: 10008
    targetPort: 10008
  selector:
    service: edge-router
status:
  loadBalancer: {}
