apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: orders
  name: orders
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 10002
  selector:
    service: orders
status:
  loadBalancer: {}
