apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: orders-db
  name: orders-db
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: orders-db
status:
  loadBalancer: {}
