apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    service: queue-master
  name: queue-master
spec:
  replicas: 1
  selector:
    service: queue-master
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: queue-master
    spec:
      containers:
      - env:
        - name: APP_OPTIONS
          value: --port=10004 --spring.rabbitmq.host=rabbitmq.sock-prod
        - name: JAVA_APP_JAR
          value: queue-master.jar
        image: ' '
        name: queue-master
        resources: {}
        ports:
        - containerPort: 10004
          hostPort: 10004
          protocol: TCP
        livenessProbe:
          httpGet:
            host: localhost
            path: /health
            port: 10004
            scheme: HTTP
          initialDelaySeconds: 200
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            host: localhost
            path: /health
            port: 10004
            scheme: HTTP
          initialDelaySeconds: 200
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /tmp
          name: queue-master-tmpfs0
      hostNetwork: true
      restartPolicy: Always
      volumes:
      - emptyDir:
          medium: Memory
        name: queue-master-tmpfs0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - queue-master
      from:
        kind: ImageStreamTag
        name: queue-master:latest
    type: ImageChange
status: {}
