apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    service: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: rabbitmq
    spec:
      nodeSelector:
        kubernetes.io/hostname: 192.168.64.2
      containers:
      - image: ' '
        name: rabbitmq
        resources: {}
        ports:
        - containerPort: 5672
          hostPort: 5672
          protocol: TCP
        livenessProbe:
          exec:
            command:
              - rabbitmqctl
              - status
          initialDelaySeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
              - rabbitmqctl
              - status
          initialDelaySeconds: 10
          timeoutSeconds: 1
        securityContext: 
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-tmp
      hostNetwork: true
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /tmp/rabbitmq
        name: rabbitmq-tmp
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - rabbitmq
      from:
        kind: ImageStreamTag
        name: rabbitmq:3
    type: ImageChange
status: {}
