apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    service: user
  name: user
spec:
  replicas: 1
  selector:
    service: user
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: user
    spec:
      containers:
      - args:
        - scripts/run
        - -port=10006
        env:
        - name: HATEAOS
          value: user.sock-prod:8080
        - name: USER_DATABASE
          value: mongodb
        - name: MONGO_HOST
          value: user-db.sock-prod:27017
        - name: ZIPKIN
          value: http://zipkin.sock-prod:9411/api/v1/spans
        image: ' '
        name: user
        resources: {}
        ports:
        - containerPort: 10006
          hostPort: 10006
          protocol: TCP
        livenessProbe:
          httpGet:
            host: localhost
            path: /health
            port: 10006
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            host: localhost
            path: /health
            port: 10006
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
      hostNetwork: true
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - user
      from:
        kind: ImageStreamTag
        name: user:latest
    type: ImageChange
status: {}
