apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    service: user-db
  name: user-db
spec:
  replicas: 1
  selector:
    service: user-db
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: user-db
    spec:
      containers:
      - image: ' '
        name: user-db
        resources: {}
        volumeMounts:
        - mountPath: /data/configdb
          name: user-db-empty0
        - mountPath: /data/db
          name: user-db-empty1
        - mountPath: /data/db-users
          name: user-db-empty2
        - mountPath: /tmp
          name: user-db-tmpfs0
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: user-db-empty0
      - emptyDir: {}
        name: user-db-empty1
      - emptyDir: {}
        name: user-db-empty2
      - emptyDir:
          medium: Memory
        name: user-db-tmpfs0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - user-db
      from:
        kind: ImageStreamTag
        name: user-db:latest
    type: ImageChange
status: {}
